# 1. Load the dataset (iris.csv).

In [1]:
from sklearn.datasets import load_iris

In [2]:
data = load_iris()
print (data.feature_names)
print (data.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


converting the iris dataset into pandas dataframe

In [3]:
import pandas as pd
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = pd.Series(data.target)

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

# 2. Split dataset into test and train (20:80).

In [5]:
X = df.iloc[:,0:4]
y = df.iloc[:,4:5]

In [6]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [7]:
y

target
0         0
1         0
2         0
3         0
4         0
..      ...
145       2
146       2
147       2
148       2
149       2

[150 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state = 4)

# 3. Build KNN classifier with k value as 2 for identifying the flower Species.

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
knn2 = KNeighborsClassifier(n_neighbors = 2)

In [12]:
knn2.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=2)

# 4. Build KNN classifier with k value as 4 for identifying the flower Species.

In [13]:
knn4 = KNeighborsClassifier(n_neighbors = 4)

In [14]:
knn4.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=4)

# 5. Evaluate the step-3 and step-4.

In [15]:
knn2.score(X_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9333333333333333

In [16]:
knn4.score(X_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9666666666666667

# 6. Design a method for calculating the distance between data points for the  given dataset

In [17]:
from scipy.spatial.distance import cdist

# Calculate the Euclidean distance between all pairs of points in X_train and X_test
distances = cdist(X_test, X_train, metric='euclidean')

print(distances)

[[1.61554944 4.96487663 0.55677644 ... 0.31622777 0.98488578 1.70587221]
 [3.1638584  1.2922848  4.66368953 ... 4.65832588 4.62493243 5.73498038]
 [2.6        5.74282161 0.82462113 ... 1.01488916 0.50990195 0.678233  ]
 ...
 [3.50142828 1.08627805 5.08527285 ... 5.05074252 5.07346036 6.18223261]
 [3.11287648 0.87749644 4.67653718 ... 4.70956474 4.70850295 5.82151183]
 [0.87749644 4.27434205 1.161895   ... 1.07703296 1.62172747 2.48797106]]


# 7. Design a method for finding the nearest neighbours of a given data point  using the above method.

In [18]:
import numpy as np

In [19]:
# Define a function to find the k nearest neighbors of a given point
def find_nearest_neighbors(X_train, x, k):
    distances = cdist(X_train, [x], metric='euclidean')
    indices = np.argsort(distances.ravel())[:k]
    return indices

# Find the k nearest neighbors of each point in the test set
k = 3
for i, x in X_test.iterrows():
    indices = find_nearest_neighbors(X_train.values, x.values, k)
    print(f"The {k} nearest neighbors of the {i+1}th data point in the test set are: {X_train.iloc[indices]}")

The 3 nearest neighbors of the 129th data point in the test set are:      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
132                6.4               2.8                5.6               2.2
104                6.5               3.0                5.8               2.2
103                6.3               2.9                5.6               1.8
The 3 nearest neighbors of the 19th data point in the test set are:     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
10                5.4               3.7                1.5               0.2
48                5.3               3.7                1.5               0.2
31                5.4               3.4                1.5               0.4
The 3 nearest neighbors of the 131th data point in the test set are:      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
102                7.1               3.0                5.9               2.1
125               

The 3 nearest neighbors of the 42th data point in the test set are:     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
8                 4.4               2.9                1.4               0.2
38                4.4               3.0                1.3               0.2
45                4.8               3.0                1.4               0.3
The 3 nearest neighbors of the 17th data point in the test set are:     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
10                5.4               3.7                1.5               0.2
48                5.3               3.7                1.5               0.2
33                5.5               4.2                1.4               0.2
The 3 nearest neighbors of the 21th data point in the test set are:     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
31                5.4               3.4                1.5               0.4
27                5.2     

In [23]:
# Assume that X_train and y_train are already defined

x_new = [[5.1, 3.5, 1.4, 0.2]]

# Calculate the distances between x_new and all the training data points
distances = cdist(x_new, X_train, metric='euclidean')

# Find the k nearest neighbors of x_new
k = 3
if len(distances[0]) >= k:
    indices = np.argsort(distances.ravel())[:k]
    nearest_neighbors = y_train.reset_index(drop=True)[indices]
    # Take a majority vote among the k nearest neighbors and assign the class label that occurs most frequently as the predicted class label for x_new
    predicted_class = nearest_neighbors.mode()[0]
else:
    print("Error: Not enough data points to find k nearest neighbors")

print(f"The predicted class label for the new data point is: {predicted_class}")

KeyError: "None of [Int64Index([101, 76, 44], dtype='int64')] are in the [columns]"