<img src="download.png">

|Programme| Semester |  Course  | Code|Faculty|RgNo|Name 
|---------|--------------|--------------------|--------|------------|---------|------------|
|M. C. A. |WINTER 2023-24|Machine Learning Lab|ITA 6016|Dr. Rajesh M|22MCA1054|Pratik Bharadwaj|


### Machine Learning lab Excersise 1
 

In [1]:
import pandas as pd
import numpy as np

# QUESTION :-1 

## 1.  Create  two  random  numpy  array  of  integers  X  and  Y;  check  whether they are equal or not?

In [2]:
arr = np.random.randint(8)

In [3]:
arr1 = np.random.randint(9) 

In [4]:
print(arr)

4


In [5]:
print(arr1)

0


In [6]:
equal = np.array_equiv(arr, arr1)

In [7]:
print("22MCA1054_Pratik_Bharadwaj")
print(equal)

22MCA1054_Pratik_Bharadwaj
False


# QUESTION :-2 

## 2.  Create  a  numpy  array  with  zeros  and  make  it  immutable  and  check whether able to change the values or not. 

In [8]:
arr2 = np.zeros(3)  

In [9]:
arr2

array([0., 0., 0.])

In [10]:
print("22MCA1054_Pratik_Bharadwaj")
arr2.flags.writeable = False
arr2[0] = 1
# Gives: ValueError: assignment destination is read-only

22MCA1054_Pratik_Bharadwaj


ValueError: assignment destination is read-only

# QUESTION :-3

## 3. Create a random numpy array Y of integers with size `10` and replace the maximum value by 100 and minimum value by 0.

In [11]:
Y = np.random.randint(low=0, high=101, size=10)

In [12]:
Y

array([19, 31, 66, 56, 76,  1, 95, 37, 63, 59])

In [13]:
# find the index of the maximum and minimum values
max_idx = np.argmax(Y)
min_idx = np.argmin(Y)

In [14]:
# replace the maximum value by 100 and minimum value by 0
Y[max_idx] = 100
Y[min_idx] = 0


In [15]:
print("22MCA1054_Pratik_Bharadwaj")
Y

22MCA1054_Pratik_Bharadwaj


array([ 19,  31,  66,  56,  76,   0, 100,  37,  63,  59])

# QUESTION :-4

## 4.  Write  a  program  to  find  the  closest  value  to  a  given  value  from  a numpy array.

In [16]:
arr4= np.array([5,9,8,16,4])

In [17]:
n = int(input("enter the value of N: "))
pratik = (np.abs(arr4-n))
index = pratik.argmin()
print("value nearest to the N in Array: ", arr4[index])
print("index of the value:",index)

enter the value of N: 14
value nearest to the N in Array:  16
index of the value: 3


In [18]:
print("22MCA1054_Pratik_Bharadwaj")
pratik

22MCA1054_Pratik_Bharadwaj


array([ 9,  5,  6,  2, 10])

# QUESTION :-5 

## 5. Write a program to subtract the mean of each row of a matrix.

In [19]:
matrix = np.array([[1,2,3,4],[6,7,8,9],[5,6,7,8]])
matrix

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [5, 6, 7, 8]])

In [20]:
#for row 0
np.mean(matrix[0])

2.5

In [21]:
a=matrix[0]-np.mean(matrix[0])
a

array([-1.5, -0.5,  0.5,  1.5])

In [22]:
#for row 1
np.mean(matrix[1])

7.5

In [23]:
b=matrix[1]-np.mean(matrix[1])
b

array([-1.5, -0.5,  0.5,  1.5])

In [24]:
#for row 2
np.mean(matrix[2])

6.5

In [25]:
c=matrix[2]-np.mean(matrix[2])
c

array([-1.5, -0.5,  0.5,  1.5])

In [26]:
#matrix after subtraction mean from each row of a matrix
print("22MCA1054_Pratik_Bharadwaj")
np.array([a,b,c])

22MCA1054_Pratik_Bharadwaj


array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

# QUESTION :-6

## 6.  Write  a  program  to  convert  the  index  of  a  series  into  a  column  of  a dataframe.

In [27]:
n = pd.Series(['pratik', 'bharadwaj', '22MCA1054'],name='st_details')

In [28]:
n

0       pratik
1    bharadwaj
2    22MCA1054
Name: st_details, dtype: object

In [29]:
df = n.to_frame().reset_index()

In [30]:
#note index of series is taken as the deafualt index
df

index st_details
0      0     pratik
1      1  bharadwaj
2      2  22MCA1054

# QUESTION :-7

## 7. Write a program to find out the items of seriesX not present in series Y?

In [31]:
x = pd.Series([1,2,3,4,5,6])

In [32]:
x

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [33]:
y = pd.Series([1,2,3,4,7,8])

In [34]:
y

0    1
1    2
2    3
3    4
4    7
5    8
dtype: int64

In [35]:
# Using Bitwise NOT operator
# Along with pandas.isin()
print("\nItems of x not present in y:")
res = x[~x.isin(y)]
print(res)
print("\n22MCA1054_Pratik_Bharadwaj")


Items of x not present in y:
4    5
5    6
dtype: int64

22MCA1054_Pratik_Bharadwaj


# QUESTION :-8 

## 8.  Write  a  program  to  find  out  the  minimum,  25th  percentile,  median, 75th, and max of a numeric series?

In [36]:
ser=pd.Series(range(10))
print("22MCA1054_Pratik_Bharadwaj")

22MCA1054_Pratik_Bharadwaj


In [37]:
df=pd.DataFrame(ser)
df.describe()

0
count  10.00000
mean    4.50000
std     3.02765
min     0.00000
25%     2.25000
50%     4.50000
75%     6.75000
max     9.00000

# QUESTION :-9

## 9.  Write  a  program  to  keep  only  top  2  most  frequent  values  as  it  is  and replace everything else as ‘Other’?

In [38]:
ser = pd.Series(np.random.randint(1, 5, [12]))
print("series intially: \n",ser,'\n\n')

print("Top 2 Freq:\n", ser.value_counts(),'\n')
ser[~ser.isin(ser.value_counts().index[:2])] = 'Other'
print("matrix after modification:\n",ser)
print("\n22MCA1054_Pratik_Bharadwaj")

series intially: 
 0     1
1     1
2     4
3     2
4     2
5     2
6     4
7     1
8     3
9     3
10    1
11    2
dtype: int32 


Top 2 Freq:
 1    4
2    4
4    2
3    2
dtype: int64 

matrix after modification:
 0         1
1         1
2     Other
3         2
4         2
5         2
6     Other
7         1
8     Other
9     Other
10        1
11        2
dtype: object

22MCA1054_Pratik_Bharadwaj


# QUESTION :-10

## 10.  Write  a  program  to  convert  the  first  character  of  each  element  in  a series to uppercase

In [39]:
sr = pd.Series(["pratik", "bharadwaj", "22MCA1054", "mca"], dtype="string")

In [40]:
sr.str.capitalize()

0       Pratik
1    Bharadwaj
2    22mca1054
3          Mca
dtype: string